### PR TITLE
Removed non-deterministic behavior by replacing `Math.random` with a precompiled table of numbers.

### PR DESCRIPTION
**Pull request by parro-it**
I was not able to test a package because this module used to call `Math.random()` in order to
shuffle space division between words when justifying text.

I replaced `Math.random` call to read values from a precompiled table.
This way spaces are evenly distributed as before, but in a  deterministic manner.

### CODE REVIEW

**Comment by doowb** [comment]
I think this is good idea. Since this feature is to make testing easier, maybe we can just create an option (e.g. `options.random`) that is an optional way to replace `Math.random`. Then other libs can pass in their own `random` generator:

```js
function random() {
  return table[lastRandom % table.length];
}

justify(someLongText, {random: random});
```

**Comment by parro-it** [comment]
@doowb I like the idea of the option, I'll add it later...
What do you think could be a good default value for the option, the deterministic function I implemented, or `Math.random`?

**Comment by doowb** [comment]
I think `Math.random` to keep it the same.

**Comment by jonschlinkert** [comment]
neat! I like the ideas, thanks!

**Comment by jonschlinkert** [comment]
oh, just noticed this comment...

> This way spaces are evenly distributed as before, but in a deterministic manner.

IMHO it's better to randomly distribute spaces, to avoid pushing all of the "extra" spaces to the right or left side of a line. If spaces are distributed evenly, then it's possible for a "wide column" of empty spaces to be created. Hope that makes sense. 

In any case, I think you guys are on the right track, and I like the idea of making it an option. thanks again!

**Comment by jonschlinkert** [comment]
> I was not able to test a package because this module used to call Math.random() in order to
> shuffle space division between words when justifying text.

Would it be sufficient to measure line lengths?

**Comment by parro-it** [comment]
> neat! I like the ideas, thanks!

You're welcome, I'm glad you like it :smile: 

> IMHO it's better to randomly distribute spaces, to avoid pushing all of the "extra" spaces to the right or  left side of a line. If spaces are distributed evenly, then it's possible for a "wide column" of empty 
> spaces to be created. Hope that makes sense.

Sorry, I used the wrong word, I really should improve my english. Anyway, spaces are distributed as before, I used a table a random numbers created at design-time to replace the runtime-created ones.
It's a technique used in games to avoid costly random calls (by the way, this change should also have some performance gains, but I've not measured it)


This is the output generated using with the new feature:

```
  When this option is on,  the export  attribute shall  be set for each variable to
  which   an  assignment is performed; see the Base  Definitions volume of IEEE Std
  1003.1-2001,  Section 4.21, Variable Assignment.  If  the assignment precedes   a
  utility name in a command,  the export attribute shall not persist in the current
  execution environment after the utility  completes,   with   the  exception  that
  preceding one of the special built-in utilities   causes  the export attribute to
  persist after the built-in has completed. If the   assignment does  not precede a
  utility name in  the command, or if the   assignment is a result of the operation
  of the getopts or read utilities, the export  attribute shall  persist until  the
  variable is unset.
```

as you can see, space are applyed randomly as before...

**Comment by jonschlinkert** [comment]
published and [released as 1.0.0](https://github.com/jonschlinkert/justified/releases/tag/1.0.0). I also added a couple of options to make the library more flexible and usable. 

thanks again!

**Pull request merged**
